export var PID_TYPE = {
    PHYSICAL: 'NiFEjb83nJL4',
    CHEMISTRY: 'IfKiInEcZu9c',
    BIOLOGICAL1: 'JuFhE84jRhEh',
    BIOLOGICAL2: 'EjEViMk33jNr'
};
export var MESSAGE_TYPE = {
    SAVE_DATA: 'PHYSICS_SDK_INTERFACE_SAVE',
    SAVE_DATA_RESPONSE: 'PHYSICS_SDK_INTERFACE_SAVE_RESPONSE',
    PHYSICS_SDK_INTERFACE_FRESH_DATA: 'PHYSICS_SDK_INTERFACE_FRESH_DATA',
    ON_LOAD: 'onload'
};
